"""create core tables

Revision ID: 0b0007c4dc28
Revises: 
Create Date: 2026-08-22 00:59:25.712397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0007c4dc28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_toggle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('read_plate', sa.Boolean(), nullable=False),
    sa.Column('plate_color', sa.Boolean(), nullable=False),
    sa.Column('vehicle_class', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=True),
    sa.Column('retention_delete_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('rtsp_url', sa.String(length=512), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plate_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capture_id', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('lane', sa.String(length=32), nullable=True),
    sa.Column('plate_text_ciphertext', sa.String(length=512), nullable=True),
    sa.Column('plate_hash', sa.String(length=64), nullable=True),
    sa.Column('plate_valid', sa.Boolean(), nullable=True),
    sa.Column('det_conf', sa.Float(), nullable=True),
    sa.Column('ocr_conf', sa.Float(), nullable=True),
    sa.Column('layout', sa.String(length=8), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('color_conf', sa.Float(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=16), nullable=True),
    sa.Column('vehicle_style', sa.String(length=16), nullable=True),
    sa.Column('vehicle_style_conf', sa.Float(), nullable=True),
    sa.Column('raw_pipeline_json', sa.JSON(), nullable=True),
    sa.Column('image_asset_id', sa.Integer(), nullable=True),
    sa.Column('review_state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['image_asset_id'], ['image_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plate_reading_capture_id'), 'plate_reading', ['capture_id'], unique=True)
    op.create_index(op.f('ix_plate_reading_plate_hash'), 'plate_reading', ['plate_hash'], unique=False)
    op.create_table('price_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_group', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('block_minutes', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_hash', sa.String(length=64), nullable=False),
    sa.Column('plate_ciphertext', sa.String(length=512), nullable=False),
    sa.Column('vehicle_group', sa.String(length=16), nullable=False),
    sa.Column('vehicle_type', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_reading_id', sa.Integer(), nullable=True),
    sa.Column('exit_reading_id', sa.Integer(), nullable=True),
    sa.Column('fee_amount', sa.Integer(), nullable=True),
    sa.Column('fee_rule_snapshot', sa.JSON(), nullable=True),
    sa.Column('match_flag', sa.String(length=16), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entry_reading_id'], ['plate_reading.id'], ),
    sa.ForeignKeyConstraint(['exit_reading_id'], ['plate_reading.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_plate_hash'), 'session', ['plate_hash'], unique=False)
    op.create_index(op.f('ix_session_status'), 'session', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_status'), table_name='session')
    op.drop_index(op.f('ix_session_plate_hash'), table_name='session')
    op.drop_table('session')
    op.drop_table('price_rule')
    op.drop_index(op.f('ix_plate_reading_plate_hash'), table_name='plate_reading')
    op.drop_index(op.f('ix_plate_reading_capture_id'), table_name='plate_reading')
    op.drop_table('plate_reading')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('lane')
    op.drop_table('image_asset')
    op.drop_table('feature_toggle')
    # ### end Alembic commands ###
