def test_outbox_table_and_session_uuid():
    from app.db import Base
    import app.models  # noqa: F401
    assert "outbox" in Base.metadata.tables
    from app.models import ParkingSession
    assert "uuid" in ParkingSession.__table__.columns.keys()


def test_session_uuid_autogenerated(db_session):
    from app.models import ParkingSession
    s = ParkingSession(plate_hash="h", plate_ciphertext="x", vehicle_group="o_to_con", status="in_lot")
    db_session.add(s); db_session.commit(); db_session.refresh(s)
    assert s.uuid is not None and len(s.uuid) >= 32
